@Developement = https://localhost:7208
@Production = http://localhost:5214

### Developement 
GET {{Developement}}/message
Accept: application/json


### Production 
GET {{Production}}/message
Accept: application/json

 
### Create Department / Department With Employee 
POST {{Developement}}/Department
Content-Type: application/json
Accept: application/json
{
    "Name":"Finance",
    "Employees":
      [
         { "name":"√œ„" },
         { "name":"’›«" },
         { "name":"Õ”«„" }
      ]
}

###  Create Employee
POST {{Developement}}/employee
Content-Type: application/json
Accept: application/json
{
    "name":50,
    "DepartmentId":8
}


### Get All Employees 
GET {{Developement}}/Employees
Accept:application/json

### Get only one Employee using Id 
GET {{Developement}}/employee/1
Accept: application/json

###

PUT {{Developement}}/employee/1
Content-Type: application/json
Accept: application/json
{
    "Id":1,
    0
}


### saving related entites 

POST {{Developement}}/Department
Content-Type: application/json
accept: application/json

{
    "Name":"Finance",
    "employees":
      [
         {
         "name":"√œ„"
         },
         {
         "name":"’›«"
         },
         {
         "name":"Õ”«„"
         },

      ]
}