@Developement = https://localhost:7208
@Production = http://localhost:5214

### Developement 
GET {{Developement}}/message
Accept: application/json


### Production 
GET {{Production}}/message
Accept: application/json

 
### Create Department / Department With Employee 
POST {{Developement}}/Department
Content-Type: application/json
Accept: application/json
{
    "Name":"Finance",
    "Employees":
      [
         { "name":"√œ„" },
         { "name":"’›«" },
         { "name":"Õ”«„" }
      ]
}

###  Create Employee
POST {{Developement}}/employee
Content-Type: application/json
Accept: application/json
{
    "name":"Hatem",
    "DepartmentId":4
}

### Get All Employees  with department 
GET {{Developement}}/Employees
Accept:application/json

### Get only one Employee using Id 
GET {{Developement}}/employee/1
Accept: application/json

### update employee 
PUT {{Developement}}/employee/1
Content-Type: application/json
Accept: application/json
{
    "Id":1,
}

### Get all department with employees 
GET {{Developement}}/departments
Content-Type: application/json
Accept: application/json
 
