@Developement = https://localhost:7208
@Production = http://localhost:5214

### Developement 
GET {{Developement}}/message
Accept: application/json


### Production 
GET {{Production}}/message
Accept: application/json

 
### Create Department / Department With Employee 
POST {{Developement}}/Department
Content-Type: application/json
Accept: application/json
{
    "Name":"HR",
    "Employees":
      [
         { "name":"√œ„ „Õ„œ " },
         { "name":"’›« „Õ„œ " },
         { "name":" › ÕÌ Õ”«„" }
      ]
}




### Get all department with employees 
GET {{Developement}}/department
Content-Type: application/json
Accept: application/json

### Get department by id 
GET {{Developement}}/department/6
Content-Type: application/json
Accept: application/json



### delete department 
DELETE {{Developement}}/Department/1
Content-Type: application/json
Accept: application/json

#########################################

###  Create Employee
POST {{Developement}}/employee
Content-Type: application/json
Accept: application/json
{
    "name":"Nasser Ahmed Ali",
    "DepartmentId":1
}

### Get All Employees  with department 
GET {{Developement}}/Employee
Accept:application/json

### Get only one Employee using Id 
GET {{Developement}}/employee/1
Accept: application/json

### update employee 
PUT {{Developement}}/employee/2
Content-Type: application/json
Accept: application/json
{
    "Id":2,
    "Name":"Adam Mohamed Fathy",
    "departmentId":2
}

### delete employee 
DELETE {{Developement}}/employee/1
Content-Type: application/json
Accept: application/json



 
